# Trigger: MissingFieldError(field='sample')
# Atteso: [ERRORE] Campo obbligatorio mancante: 'sample'
#         Hint: specificare il nome del file wav...
#         Stream: stream_no_sample
#         Config: configs/error_tests/01_missing_sample.yml

composition:
  title: "test missing sample"

streams:
  - stream_id: "stream_no_sample"
    onset: 0.0
    duration: 5
    sample:        # <-- volutamente null
    distribution_mode: 'gaussian'
    density: 5
    distribution: [[0,1],[1,1]]
    pointer:
      speed_ratio: 1.0
    grain:
      duration: 0.05
      duration_range: 0.01
