# project: PGE_pino2
# saved:   2026-08-18T18:05:42.158Z
# editor:  PGE-ui

duration: 310
bpm: 120
streams:
  - stream_id: texture2
    onset: 0
    duration: 300
    sample: 001-0_0-3_0.wav
    time_mode: normalized
    density: [[[[0, 400], [100, 1000]], 1, 10, linear, {type: power, exponent: 2}]]
    grain:
      duration: 0.05
    pointer:
      speed_ratio: [[[[0, -1], [100, 2]], 1, 15, cubic, {type: geometric, ratio: 1.5}]]
      loop_start:
        type: cubic
        points: [[0, 0.9], [1, 1]]
      loop_unit: normalized
      offset_range:
        type: cubic
        points: [[0, 0], [1, 1]]
    pan_range:
      type: cubic
      points: [[0, 0], [0.5, 360], [0.75, 0], [1, 180]]
    volume: -20
    deviation_probability: null
  - stream_id: texture3
    onset: 0
    duration: 300
    sample: 001-29_5-7_5.wav
    time_mode: normalized
    density: [[[[0, 400], [100, 1000]], 1, 10, linear, {type: power, exponent: 2}]]
    grain:
      duration: 0.05
    pointer:
      speed_ratio: [[[[0, -1], [100, 0.3]], 1, 2, linear, {type: geometric, ratio: 4}]]
      loop_start:
        type: cubic
        points: [[0, 0.9], [1, 1]]
      loop_unit: normalized
      offset_range:
        type: cubic
        points: [[0, 0], [1, 1]]
    volume: -20
    deviation_probability: null
  - stream_id: stream4
    onset: 0
    duration: 60
    sample: 001-0_0-3_0.wav
    time_mode: normalized
    density: 200
    pointer:
      speed_ratio: 0.01
    pan: 70
    pan_range: 170
    volume: -20
    deviation_probability: 50
  - stream_id: stream5
    onset: 0
    duration: 200
    sample: 001-8_5-4_5.wav
    time_mode: normalized
    grain:
      duration_range: 0.2
    pointer:
      speed_ratio: 0.01
    pitch:
      ratio: 0.5
      range: 0.1
    pan: 70
    pan_range: 30
    volume: -10
    deviation_probability:
      duration: 90
      pan: 50
      reverse: 70
composition:
  title: il mondo dorme
