# project: PGE_chord_progression_test
# saved:   2026-08-18T18:04:28.643Z
# editor:  PGE-ui

duration: 164
bpm: 120
streams:
  - stream_id: A_glissando_linear
    onset: 0
    duration: 24
    sample: sinus.wav
    density: 25
    grain:
      duration: 0.1
    volume: -12
    voices:
      num_voices: 4
      pitch:
        strategy: chord_progression
        interp: linear
        voice_leading: positional
        progression: [[0, maj7], [8, min7], [16, dom7], [24, maj7]]
  - stream_id: B_blocks_step
    onset: 26
    duration: 24
    sample: sinus.wav
    density: 25
    grain:
      duration: 0.1
    volume: -12
    voices:
      num_voices: 4
      pitch:
        strategy: chord_progression
        interp: step
        voice_leading: positional
        progression: [[0, maj7], [8, min7], [16, dom7], [24, maj7]]
  - stream_id: C_glissando_cubic
    onset: 52
    duration: 24
    sample: sinus.wav
    density: 25
    grain:
      duration: 0.1
    volume: -12
    voices:
      num_voices: 4
      pitch:
        strategy: chord_progression
        interp: cubic
        voice_leading: positional
        progression: [[0, maj7], [8, min7], [16, dom7], [24, maj7]]
  - stream_id: D_vl_positional
    onset: 78
    duration: 24
    sample: sinus.wav
    density: 25
    grain:
      duration: 0.1
    volume: -12
    voices:
      num_voices: 4
      pitch:
        strategy: chord_progression
        interp: linear
        voice_leading: positional
        progression: [[0, maj7], [6, min7, 2], [12, dom9, 4], [18, maj7]]
  - stream_id: E_vl_nearest
    onset: 104
    duration: 24
    sample: sinus.wav
    density: 25
    grain:
      duration: 0.1
    volume: -12
    voices:
      num_voices: 4
      pitch:
        strategy: chord_progression
        interp: linear
        voice_leading: nearest
        progression: [[0, maj7], [6, min7, 2], [12, dom9, 4], [18, maj7]]
  - stream_id: F_full_with_root_normalized
    onset: 130
    duration: 24
    sample: sinus.wav
    time_mode: normalized
    density: 25
    grain:
      duration: 0.1
    pitch:
      semitones: [[0, 0], [0.33, 5], [0.66, 7], [1, 0]]
    volume: -12
    voices:
      num_voices: 4
      pitch:
        strategy: chord_progression
        interp: linear
        voice_leading: nearest
        progression: [[0, maj7], [0.33, maj7], [0.66, dom7], [1, maj7]]
composition:
  title: "chord_progression test (issue #86)"
